### ISSUE TITLE
Улучшить search edittext

### ISSUE THREAD

**Issue by dlfilin** [dlfilin/practicum-android-diploma-hh#35]
Советую сделать TextInputLayout вместо EditText.
В верстку что-то вроде 
            app:endIconMode="custom"
            app:endIconDrawable="@drawable/ic_search"

А в TextWatcher что-то вроде 
                if (s.isNullOrBlank())
                    binding.textLayoutName.setEndIconDrawable(R.drawable.ic_search_16)
                else
                    binding.textLayoutName.setEndIconDrawable(R.drawable.ic_clear)

**Comment by SvetlanaTimchenko** [comment]
Контроль смены иконок может быть реализован разными способами и для EditText. Это вобще не проблема.

**Comment by SvetlanaTimchenko** [comment]
из коробки к нам не приминимо. Отложили на потом.
