### ISSUE TITLE
Светлая/темная темы по Material Design

### ISSUE THREAD

**Issue by SvetlanaTimchenko** [dlfilin/practicum-android-diploma-hh#7]
- [x] от Theme.MaterialComponents.DayNight.NoActionBar

- [x] описана цветовая палитра

- [x] сделать стили для отдельных компонентов UI
- [x] использовать https://m2.material.io/components?platform=android

**Comment by SvetlanaTimchenko** [comment]
Есть вопрос по стилям отдельных компонентов.

Сделаны стили для:

1. базовый для Toolbar (в основном для текста)
2. прогресс бар
3. большая синяя кнопка
4. всплывающая синяя подсказка (в дизайне Chip)
5. кнопка Сбросить
6. меню нижней навигации
7. разделитель между меню и основной областью

Надо сделать еще какие-то стили? Например, чекбоксы, стрелочки, recycleView

**Comment by Jaroslav-89** [comment]
я думаю можно оставить так, потом, если чего то будет не хватать - добавим
